* This is a MIB description for Microchip TCP/IP Stack.
* Anyline starting without '$' is a comment.
* Line starting with $ is a command and first word after $ must be
* a valid command string.
*
* Use mib2bib to compile this file and generate binary BIB file.
*
* v1.0 supports following commands
*       $DeclareVar(<oidName>, <dataType>, <oidType>, <access>,  <oidString>)
* 
* Author                      Date                Comment
* ==========================================================================
* Nilesh Rajbharti            5/21/03             Initial (v1.0)
* Howard Schlunder            9/12/06             Testing with 3.75
* Amit Shirbhate	      3/10/09		  Snmp Version v2c Updates		 
* 


DeclareVar(<NodeName>, <NodeDataType>, <NodeType>, <NodeAccess>, <NodeOID>)

$DeclareVar(SYS_UP_TIME, TIME_TICKS, SINGLE, READONLY, 43.6.1.2.1.1.3)
$DynamicVar(SYS_UP_TIME, 250)

$DeclareVar(ENT_SPA_SIB, OID, SINGLE, READONLY, 43.6.1.2.1.1.2)
$StaticVar(ENT_SPA_SIB, 43.6.1.4.1.33183)
$AgentID(ENT_SPA_SIB, 255)


****************************************************************************
*    DISPLAY_DEVICE_INFO
****************************************************************************

$DeclareVar(DISPLAY_DEVICE_SERIAL, DWORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.1.1)
$DynamicVar(DISPLAY_DEVICE_SERIAL, 1)


$DeclareVar(DISPLAY_DEVICE_LOCATION, ASCII_STRING, SINGLE, READWRITE, 43.6.1.4.1.33183.30.1.2)
$DynamicVar(DISPLAY_DEVICE_LOCATION, 2)


$DeclareVar(DISPLAY_DEVICE_INFO_RESET_COUNTER, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.1.3)
$DynamicVar(DISPLAY_DEVICE_INFO_RESET_COUNTER, 3)



****************************************************************************
*    DIPSLAY_ENERGY_METER
****************************************************************************

$DeclareVar(DIPSLAY_TOTAL_ENERGY, DWORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.2.1)
$DynamicVar(DIPSLAY_TOTAL_ENERGY, 4)


$DeclareVar(DIPSLAY_CURRENT_ENERGY, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.2.2)
$DynamicVar(DIPSLAY_CURRENT_ENERGY, 5)


$DeclareVar(DIPSLAY_ENERGY_METER_ADDRESS, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.2.3)
$DynamicVar(DIPSLAY_ENERGY_METER_ADDRESS, 6)



****************************************************************************
*    DISPLAY_TEMPERATURE
****************************************************************************

$DeclareVar(DISPLAY_INT_TEMPERATURE, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.3.1)
$DynamicVar(DISPLAY_INT_TEMPERATURE, 7)

$DeclareVar(DISPLAY_INT_TEMPERATURE_ALARM_1_LEVEL, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.2)
$DynamicVar(DISPLAY_INT_TEMPERATURE_ALARM_1_LEVEL, 8)

$DeclareVar(DISPLAY_INT_TEMPERATURE_ALARM_1_LOGIC, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.3)
$DynamicVar(DISPLAY_INT_TEMPERATURE_ALARM_1_LOGIC, 9)

$DeclareVar(DISPLAY_INT_TEMPERATURE_ALARM_1_TRAP_SEND_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.4)
$DynamicVar(DISPLAY_INT_TEMPERATURE_ALARM_1_TRAP_SEND_AV, 10)

$DeclareVar(DISPLAY_INT_TEMPERATURE_ALARM_1_TRAP_SEND_NO_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.5)
$DynamicVar(DISPLAY_INT_TEMPERATURE_ALARM_1_TRAP_SEND_NO_AV, 11)

$DeclareVar(DISPLAY_INT_TEMPERATURE_ALARM_1_STATUS, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.3.6)
$DynamicVar(DISPLAY_INT_TEMPERATURE_ALARM_1_STATUS, 12)

$DeclareVar(DISPLAY_INT_TEMPERATURE_ALARM_2_LEVEL, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.7)
$DynamicVar(DISPLAY_INT_TEMPERATURE_ALARM_2_LEVEL, 13)


$DeclareVar(DISPLAY_INT_TEMPERATURE_ALARM_2_LOGIC, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.8)
$DynamicVar(DISPLAY_INT_TEMPERATURE_ALARM_2_LOGIC, 14)


$DeclareVar(DISPLAY_INT_TEMPERATURE_ALARM_2_TRAP_SEND_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.9)
$DynamicVar(DISPLAY_INT_TEMPERATURE_ALARM_2_TRAP_SEND_AV, 15)


$DeclareVar(DISPLAY_INT_TEMPERATURE_ALARM_2_TRAP_SEND_NO_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.10)
$DynamicVar(DISPLAY_INT_TEMPERATURE_ALARM_2_TRAP_SEND_NO_AV, 16)

$DeclareVar(DISPLAY_INT_TEMPERATURE_ALARM_2_STATUS, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.3.11)
$DynamicVar(DISPLAY_INT_TEMPERATURE_ALARM_2_STATUS, 17)

$DeclareVar(DISPLAY_EXT_TEMPERATURE, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.3.12)
$DynamicVar(DISPLAY_EXT_TEMPERATURE, 18)

$DeclareVar(DISPLAY_EXT_TEMPERATURE_ALARM_1_LEVEL, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.13)
$DynamicVar(DISPLAY_EXT_TEMPERATURE_ALARM_1_LEVEL, 19)

$DeclareVar(DISPLAY_EXT_TEMPERATURE_ALARM_1_LOGIC, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.14)
$DynamicVar(DISPLAY_EXT_TEMPERATURE_ALARM_1_LOGIC, 20)

$DeclareVar(DISPLAY_EXT_TEMPERATURE_ALARM_1_TRAP_SEND_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.15)
$DynamicVar(DISPLAY_EXT_TEMPERATURE_ALARM_1_TRAP_SEND_AV, 81)

$DeclareVar(DISPLAY_EXT_TEMPERATURE_ALARM_1_TRAP_SEND_NO_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.16)
$DynamicVar(DISPLAY_EXT_TEMPERATURE_ALARM_1_TRAP_SEND_NO_AV, 82)

$DeclareVar(DISPLAY_EXT_TEMPERATURE_ALARM_1_STATUS, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.3.17)
$DynamicVar(DISPLAY_EXT_TEMPERATURE_ALARM_1_STATUS, 83)

$DeclareVar(DISPLAY_EXT_TEMPERATURE_ALARM_2_LEVEL, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.18)
$DynamicVar(DISPLAY_EXT_TEMPERATURE_ALARM_2_LEVEL, 84)

$DeclareVar(DISPLAY_EXT_TEMPERATURE_ALARM_2_LOGIC, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.19)
$DynamicVar(DISPLAY_EXT_TEMPERATURE_ALARM_2_LOGIC, 85)

$DeclareVar(DISPLAY_EXT_TEMPERATURE_ALARM_2_TRAP_SEND_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.20)
$DynamicVar(DISPLAY_EXT_TEMPERATURE_ALARM_2_TRAP_SEND_AV, 86)

$DeclareVar(DISPLAY_EXT_TEMPERATURE_ALARM_2_TRAP_SEND_NO_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.3.21)
$DynamicVar(DISPLAY_EXT_TEMPERATURE_ALARM_2_TRAP_SEND_NO_AV, 87)

$DeclareVar(DISPLAY_EXT_TEMPERATURE_ALARM_2_STATUS, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.3.22)
$DynamicVar(DISPLAY_EXT_TEMPERATURE_ALARM_2_STATUS, 88)b


****************************************************************************
*    DISPLAY_LOGIN
****************************************************************************


$DeclareVar(DISPLAY_LOGIN_1, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.4.1)
$DynamicVar(DISPLAY_LOGIN_1, 21)


$DeclareVar(DISPLAY_LOGIN_2, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.4.2)
$DynamicVar(DISPLAY_LOGIN_2, 22)


$DeclareVar(DISPLAY_LOGIN_3, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.4.3)
$DynamicVar(DISPLAY_LOGIN_3, 23)


$DeclareVar(DISPLAY_LOGIN_4, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.4.4)
$DynamicVar(DISPLAY_LOGIN_4, 24)


$DeclareVar(DISPLAY_LOGIN_5, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.4.5)
$DynamicVar(DISPLAY_LOGIN_5, 25)


$DeclareVar(DISPLAY_LOGIN_6, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.4.6)
$DynamicVar(DISPLAY_LOGIN_6, 26)


$DeclareVar(DISPLAY_LOGIN_1_AV, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.4.7)
$DynamicVar(DISPLAY_LOGIN_1_AV, 27)


$DeclareVar(DISPLAY_LOGIN_2_AV, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.4.8)
$DynamicVar(DISPLAY_LOGIN_2_AV, 28)


$DeclareVar(DISPLAY_LOGIN_3_AV, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.4.9)
$DynamicVar(DISPLAY_LOGIN_3_AV, 29)


$DeclareVar(DISPLAY_LOGIN_4_AV, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.4.10)
$DynamicVar(DISPLAY_LOGIN_4_AV, 30)


$DeclareVar(DISPLAY_LOGIN_5_AV, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.4.11)
$DynamicVar(DISPLAY_LOGIN_5_AV, 31)


$DeclareVar(DISPLAY_LOGIN_6_AV, WORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.4.12)
$DynamicVar(DISPLAY_LOGIN_6_AV, 32)


****************************************************************************
*    DISPLAY_SPECIALS
****************************************************************************


$DeclareVar(DISPLAY_SPECIAL_STRAP_MESSAGE, ASCII_STRING, SINGLE, READONLY, 43.6.1.4.1.33183.30.5.1)
$DynamicVar(DISPLAY_SPECIAL_STRAP_MESSAGE, 33)


$DeclareVar(DISPLAY_SPECIAL_STRAP_VALUE_0, DWORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.5.2)
$DynamicVar(DISPLAY_SPECIAL_STRAP_VALUE_0, 34)


$DeclareVar(DISPLAY_SPECIAL_STRAP_VALUE_1, DWORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.5.3)
$DynamicVar(DISPLAY_SPECIAL_STRAP_VALUE_1, 35)


$DeclareVar(DISPLAY_SPECIAL_STRAP_VALUE_2, DWORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.5.4)
$DynamicVar(DISPLAY_SPECIAL_STRAP_VALUE_2, 36)


$DeclareVar(COMMAND, OCTET_STRING, SINGLE, READWRITE, 43.6.1.4.1.33183.30.5.5)
$DynamicVar(COMMAND, 37)



****************************************************************************
*    DISPLAY_ENERGY_METER_IMPULSE
****************************************************************************


$DeclareVar(DISPLAY_IMPULSE_ENERGYMETER, DWORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.6.1)
$DynamicVar(DISPLAY_IMPULSE_ENERGYMETER, 38)


$DeclareVar(DISPLAY_IMPULSE_NERGYMETER_TOTAL_ENERGY, DWORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.6.2)
$DynamicVar(DISPLAY_IMPULSE_NERGYMETER_TOTAL_ENERGY, 39)


$DeclareVar(DISPLAY_IMPULSE_NERGYMETER_IMPULS_PERKWTH, DWORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.6.3)
$DynamicVar(DISPLAY_IMPULSE_NERGYMETER_IMPULS_PERKWTH, 40)


****************************************************************************
*    DISPLAY_ETHERNET_SETTINGS
****************************************************************************

$DeclareVar(DISPLAY_ETHERNET_SETTINGS_IPADDRESS, IP_ADDRESS, SINGLE, READWRITE, 43.6.1.4.1.33183.30.7.1)
$DynamicVar(DISPLAY_ETHERNET_SETTINGS_IPADDRESS, 41)


$DeclareVar(DISPLAY_ETHERNET_SETTINGS_NETMASK, IP_ADDRESS, SINGLE, READWRITE, 43.6.1.4.1.33183.30.7.2)
$DynamicVar(DISPLAY_ETHERNET_SETTINGS_NETMASK, 42)


$DeclareVar(DISPLAY_ETHERNET_SETTINGS_DEFGATW, IP_ADDRESS, SINGLE, READWRITE, 43.6.1.4.1.33183.30.7.3)
$DynamicVar(DISPLAY_ETHERNET_SETTINGS_DEFGATW, 43)




****************************************************************************
*    DISPLAY_SNMP_SETTINGS
****************************************************************************

$DeclareVar(DISPLAY_SNMP_SETTINGS_READ_PORT, DWORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.8.1)
$DynamicVar(DISPLAY_SNMP_SETTINGS_READ_PORT, 44)


$DeclareVar(DISPLAY_SNMP_SETTINGS_WRITE_PORT, DWORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.8.2)
$DynamicVar(DISPLAY_SNMP_SETTINGS_WRITE_PORT, 45)


$DeclareVar(DISPLAY_SNMP_SETTINGS_READ_COMMUNITY_NAME, OCTET_STRING, SINGLE, READWRITE, 43.6.1.4.1.33183.30.8.3)
$DynamicVar(DISPLAY_SNMP_SETTINGS_READ_COMMUNITY_NAME, 46)


$DeclareVar(DISPLAY_SNMP_SETTINGS_WRITE_COMMUNITY_NAME, OCTET_STRING, SINGLE, READWRITE, 43.6.1.4.1.33183.30.8.4)
$DynamicVar(DISPLAY_SNMP_SETTINGS_WRITE_COMMUNITY_NAME, 47)


$DeclareVar(DISPLAY_SNMP_SETTINGS_TRAP_SERVER1, IP_ADDRESS, SINGLE, READWRITE, 43.6.1.4.1.33183.30.8.5)
$DynamicVar(DISPLAY_SNMP_SETTINGS_TRAP_SERVER1, 48)


$DeclareVar(DISPLAY_SNMP_SETTINGS_TRAP_SERVER2, IP_ADDRESS, SINGLE, READWRITE, 43.6.1.4.1.33183.30.8.6)
$DynamicVar(DISPLAY_SNMP_SETTINGS_TRAP_SERVER2, 49)


$DeclareVar(DISPLAY_SNMP_SETTINGS_TRAP_SERVER3, IP_ADDRESS, SINGLE, READWRITE, 43.6.1.4.1.33183.30.8.7)
$DynamicVar(DISPLAY_SNMP_SETTINGS_TRAP_SERVER3, 50)


$DeclareVar(DISPLAY_SNMP_SETTINGS_TRAP_SERVER4, IP_ADDRESS, SINGLE, READWRITE, 43.6.1.4.1.33183.30.8.8)
$DynamicVar(DISPLAY_SNMP_SETTINGS_TRAP_SERVER4, 51)


$DeclareVar(DISPLAY_SNMP_SETTINGS_TRAP_SERVER5, IP_ADDRESS, SINGLE, READWRITE, 43.6.1.4.1.33183.30.8.9)
$DynamicVar(DISPLAY_SNMP_SETTINGS_TRAP_SERVER5, 52)


****************************************************************************
*    DISPLAY_WRK_SETTINGS
****************************************************************************

$DeclareVar(DISPLAY_LOGIN_1_STAT_OF_AV, BYTE, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.1)
$DynamicVar(DISPLAY_LOGIN_1_STAT_OF_AV, 53)


$DeclareVar(DISPLAY_LOGIN_2_STAT_OF_AV, DWORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.2)
$DynamicVar(DISPLAY_LOGIN_2_STAT_OF_AV, 54)


$DeclareVar(DISPLAY_LOGIN_3_STAT_OF_AV, DWORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.3)
$DynamicVar(DISPLAY_LOGIN_3_STAT_OF_AV, 55)


$DeclareVar(DISPLAY_LOGIN_4_STAT_OF_AV, DWORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.4)
$DynamicVar(DISPLAY_LOGIN_4_STAT_OF_AV, 56)


$DeclareVar(DISPLAY_LOGIN_5_STAT_OF_AV, DWORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.5)
$DynamicVar(DISPLAY_LOGIN_5_STAT_OF_AV, 57)


$DeclareVar(DISPLAY_LOGIN_6_STAT_OF_AV, DWORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.6)
$DynamicVar(DISPLAY_LOGIN_6_STAT_OF_AV, 58)


$DeclareVar(DISPLAY_LOGIN_1_TRAP_SEND_OF_AV, BYTE, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.7)
$DynamicVar(DISPLAY_LOGIN_1_TRAP_SEND_OF_AV, 59)


$DeclareVar(DISPLAY_LOGIN_2_TRAP_SEND_OF_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.8)
$DynamicVar(DISPLAY_LOGIN_2_TRAP_SEND_OF_AV, 60)


$DeclareVar(DISPLAY_LOGIN_3_TRAP_SEND_OF_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.9)
$DynamicVar(DISPLAY_LOGIN_3_TRAP_SEND_OF_AV, 61)


$DeclareVar(DISPLAY_LOGIN_4_TRAP_SEND_OF_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.10)
$DynamicVar(DISPLAY_LOGIN_4_TRAP_SEND_OF_AV, 62)


$DeclareVar(DISPLAY_LOGIN_5_TRAP_SEND_OF_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.11)
$DynamicVar(DISPLAY_LOGIN_5_TRAP_SEND_OF_AV, 63)


$DeclareVar(DISPLAY_LOGIN_6_TRAP_SEND_OF_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.12)
$DynamicVar(DISPLAY_LOGIN_6_TRAP_SEND_OF_AV, 64)


$DeclareVar(DISPLAY_LOGIN_1_TRAP_SEND_OF_NO_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.13)
$DynamicVar(DISPLAY_LOGIN_1_TRAP_SEND_OF_NO_AV, 65)


$DeclareVar(DISPLAY_LOGIN_2_TRAP_SEND_OF_NO_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.14)
$DynamicVar(DISPLAY_LOGIN_2_TRAP_SEND_OF_NO_AV, 66)


$DeclareVar(DISPLAY_LOGIN_3_TRAP_SEND_OF_NO_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.15)
$DynamicVar(DISPLAY_LOGIN_3_TRAP_SEND_OF_NO_AV, 67)


$DeclareVar(DISPLAY_LOGIN_4_TRAP_SEND_OF_NO_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.16)
$DynamicVar(DISPLAY_LOGIN_4_TRAP_SEND_OF_NO_AV, 68)


$DeclareVar(DISPLAY_LOGIN_5_TRAP_SEND_OF_NO_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.17)
$DynamicVar(DISPLAY_LOGIN_5_TRAP_SEND_OF_NO_AV, 69)


$DeclareVar(DISPLAY_LOGIN_6_TRAP_SEND_OF_NO_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.9.18)
$DynamicVar(DISPLAY_LOGIN_6_TRAP_SEND_OF_NO_AV, 70)


****************************************************************************
*    DISPLAY_HUMIDITY
****************************************************************************

$DeclareVar(DISPLAY_HUMIDITY_SENSOR_VALUE, DWORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.10.1)
$DynamicVar(DISPLAY_HUMIDITY_SENSOR_VALUE, 71)


$DeclareVar(DISPLAY_ALARM_HUMIDITY_LEVEL, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.10.2)
$DynamicVar(DISPLAY_ALARM_HUMIDITY_LEVEL, 72)


$DeclareVar(DISPLAY_ALARM_HUMIDITY_LOGIC, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.10.3)
$DynamicVar(DISPLAY_ALARM_HUMIDITY_LOGIC, 73)


$DeclareVar(DISPLAY_ALARM_HUMIDITY_STATUS, DWORD, SINGLE, READONLY, 43.6.1.4.1.33183.30.10.4)
$DynamicVar(DISPLAY_ALARM_HUMIDITY_STATUS, 74)


$DeclareVar(DISPLAY_ALARM_HUMIDITY_TRAP_SEND_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.10.5)
$DynamicVar(DISPLAY_ALARM_HUMIDITY_TRAP_SEND_AV, 75)


$DeclareVar(DISPLAY_ALARM_HUMIDITY_TRAP_SEND_NO_AV, WORD, SINGLE, READWRITE, 43.6.1.4.1.33183.30.10.6)
$DynamicVar(DISPLAY_ALARM_HUMIDITY_TRAP_SEND_NO_AV, 76)


